### PR TITLE
Add usb-otg to twrp.fstab

### PR DESCRIPTION
**Pull request by handymenny**
Change-Id: I6f459d16acf2a3893138c4cdce0b2c47020d2f5c

### CODE REVIEW

**Comment by Agontuk** [comment]
usb otg works for you ?

**Comment by handymenny** [comment]
Yes, it works. Some pen drives are "rejected due to insufficient available bus power" (~500 mA).

**Comment by Agontuk** [comment]
So it works in rom also? I tried once but didn't work for me.

**Comment by handymenny** [comment]
Yes, it works fine.

**Comment by Agontuk** [comment]
manually merged it after some formatting.

**Pull request closed without merging**
