### PR TITLE
Slim bootrec-led and update recovery stuff

### PR DESCRIPTION
**Pull request by handymenny**

### CODE REVIEW

**Comment by Agontuk** [comment]
We (Aosx team) agreed to keep all the configuration files in one folder like FXP repo. So I don't want to create separate dir for recovery stuff.
bootrec and recovery.rc file looks good to me. If you're sure they work, create a new pull request with them in the config dir, I'll check back later :)

**Comment by handymenny** [comment]
I made that change because my last twrp builds lacked twrp.fstab and postrecoveryboot.
I'll try again without it.

**Comment by handymenny** [comment]
I made a new build of twrp, twrp.fstab, init.recovery.st-ericcson and postrecoveryboot aren't present.
EDIT: Seems to be my problem, you don't need to worry about it.

**Comment by handymenny** [comment]
In my opinion this pull request is ready to merge.

**Comment by Agontuk** [comment]
why modemfs needs to be mounted ? We're in recovery, there's no need for it.

**Comment by handymenny** [comment]
For a correct sepolicy, everithing under /modemfs should be labelled, but this label can cause issue if is flashed a rom with selinux enabled without "type modem_file, fs_type;".
The ability to backup/restore modemfs can help to remove the security context of files and dir under /modemfs .

**Comment by Agontuk** [comment]
Alright, but I'm not gonna add any selinux commit for now. I'll cherry pick the other commits you made, while you keep working on selinux until it's ready. Good work, thanks.

**Comment by handymenny** [comment]
I have updated the pull request

**Comment by Agontuk** [comment]
I'm busy right now, gonna test and merge it later.

**Comment by Agontuk** [comment]
Are you sure recovery script is working? In my case, it wasn't copied into recovery ramdisk.

**Comment by HandyMenny** [comment]
In my case even twrp.fstab and postrecoveryboot are copied.

**Comment by handymenny** [comment]
Now works. The fact that my last twrp builds lacked twrp.fstab and postrecoveryboot, sent me astray.
It has to be copied to root instead of recovery/root .

**Comment by Agontuk** [comment]
Tested it, but this doesn't change anything. Only sets the correct vendor, product. I don't think it's required in recovery, does this have any effect on your end ?

**Comment by handymenny** [comment]
On windows 8.1 I had to manually install Nexus 4 driver in order to use ADB.
The driver weren't automatically recognized, I had to search "vid 18D1 pid 4EE2" to understand that I needed Nexus 4 driver.

**Pull request merged**
